name: "triggered workflow"

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'  

jobs:
    printInputs:
      runs-on: ubuntu-latest
      steps:
      - run: |
          echo "Tags: ${{ github.event.inputs.tags }}" 
